(function() {var implementors = {};
implementors["chalk_integration"] = [{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"struct\" href=\"chalk_integration/error/struct.ChalkError.html\" title=\"struct chalk_integration::error::ChalkError\">ChalkError</a>","synthetic":false,"types":["chalk_integration::error::ChalkError"]},{"text":"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"chalk_integration/error/enum.RustIrError.html\" title=\"enum chalk_integration::error::RustIrError\">RustIrError</a>","synthetic":false,"types":["chalk_integration::error::RustIrError"]}];
implementors["chalk_solve"] = [{"text":"impl&lt;TF:&nbsp;<a class=\"trait\" href=\"chalk_ir/family/trait.TypeFamily.html\" title=\"trait chalk_ir::family::TypeFamily\">TypeFamily</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"chalk_solve/coherence/enum.CoherenceError.html\" title=\"enum chalk_solve::coherence::CoherenceError\">CoherenceError</a>&lt;TF&gt;","synthetic":false,"types":["chalk_solve::coherence::CoherenceError"]},{"text":"impl&lt;TF:&nbsp;<a class=\"trait\" href=\"chalk_ir/family/trait.TypeFamily.html\" title=\"trait chalk_ir::family::TypeFamily\">TypeFamily</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/std/error/trait.Error.html\" title=\"trait std::error::Error\">Error</a> for <a class=\"enum\" href=\"chalk_solve/wf/enum.WfError.html\" title=\"enum chalk_solve::wf::WfError\">WfError</a>&lt;TF&gt;","synthetic":false,"types":["chalk_solve::wf::WfError"]}];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        })()